name: Test

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        luaVersion: [ "5.1", "5.2", "5.3" ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup lua ${{ matrix.luaVersion }}
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - name: Test
        run: lua hsluv_test.lua
